crazy_book_club/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('', include('crazy_book_club_app.urls')),
]

crazy_book_club_app/urls.py
'''defines URL patterns for crazy_book_club_app'''
from django.contrib import admin
from django.urls import URLPattern, path 
from . import views 

app_name='crazy_book_club_app'
urlpatterns= [ 
    #home page
    path('', views.index, name='index'),
    #page that shows all books
    path('booknames/', views.booknames, name='booknames'),
    #page for each book
    path('booknames/<int:bookname_id>/', views.bookname, name='bookname'),
    #page for adding new review
    path('new_book/', views.new_book, name='new_book'),
    #page for adding new review
    path('new_review/<int:bookname_id>/', views.new_review, name='new_review'),
    #page for editing reviews
    path('edit_review/<int:review_id>/', views.edit_review, name='edit_review'),
]

#this is a comment to test git

users/urls.py
'''defines url patterns for users'''

from django.urls import path, include
from . import views

app_name='users'
urlpatterns=[ 
    #include default auth-urls
    path('', include('django.contrib.auth.urls')),
    #registration page
    path('register/', views.register, name='register'),

]

crazy_book_club_app/models.py
from django.db import models
from django.contrib.auth.models import User

class Book(models.Model):
    ##description for a book
    #name of book
    name=models.CharField(max_length=400)
    #name of author
    authors=models.JSONField() 
    #publishing year for the book
    year_published=models.IntegerField()
    #date and time on which the model was created and modified.
    date_added=models.DateTimeField(auto_now_add=True)
    date_modified=models.DateTimeField(auto_now=True)
    #the person who created the class instance
    owner=models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        ##returns the model for the book as a string.
        return f'{self.name}, {self.authors}, {self.year_published}, {self.date_added}'

class Review(models.Model):
    #Description for a review
    #Place to store review
    my_review=models.TextField()
    #place to store a star rating for a book
    stars=models.IntegerField()
    #check false if you have completed the book
    unfinished=models.BooleanField()
    #date and time for when the review was added and modified
    date_added=models.DateTimeField(auto_now_add=True)
    date_modified=models.DateTimeField(auto_now=True)
    #a variable to link the review to a book in the database
    book=models.ForeignKey(Book, on_delete=models.CASCADE)
    owner=3 #models.ForeignKey(User, on_delete=models.CASCADE)
    #meta field changes the name of the model into plural.
    class Meta:
        verbose_name_plural='Reviews'
 

    def __str__(self):
        #returns representation of the model Review.
        return f'Review for {self.book}'

crazy_book_club_app/forms.py
from django import forms
from .models import Book, Review

class BookForm(forms.ModelForm):
    class Meta:
        model=Book
        fields=['name', 'authors', 'year_published']
        labels={'name':'', 'authors':'', 'year_published':''}

class ReviewForm(forms.ModelForm):
    class Meta:
        model= Review
        fields=['my_review','stars','unfinished']
        labels={'my_review':'','stars':'','unfinished':''}
        widgets={'text':forms.Textarea(attrs={'cols':80})}

crazy_book_club_app/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.decorators import login_required
from django.http import Http404

from .models import Book, Review
from .forms import BookForm, ReviewForm
# Create your views here.

def index(request):
    '''the home page for crazy book club app'''
    return render(request,'crazy_book_club_app/index.html')

@login_required
def booknames(request):
    '''show all booknames'''
    booknames=Book.objects.filter(owner=request.user).order_by('date_added')
    context= {'booknames':booknames}
    return render(request, 'crazy_book_club_app/booknames.html', context)

@login_required   
def bookname(request, bookname_id):
    '''shows a single book and its reviews'''
    bookname=Book.objects.get(id=bookname_id)
    #assuring the bookname belongs to the correct user
    if bookname.owner!=request.user:
        raise Http404
    reviews=bookname.review_set.order_by('-date_added')
    context={'bookname':bookname, 'reviews':reviews}
    return render(request, 'crazy_book_club_app/bookname.html',context)

@login_required
def new_book(request):
    '''adds a new book'''
    if request.method != 'POST':
        #no data submitted--> create blank form
        form=BookForm()
    else:
        #POST data submitted --> process data
        form=BookForm(data=request.POST)
        if form.is_valid():
            new_book=form.save(commit=False)
            new_book.owner=request.user
            new_book.save()
            return redirect('crazy_book_club_app:booknames')
        #display a blank or invalid form:
    context={'form':form}
    return render(request,'crazy_book_club_app/new_book.html',context)

@login_required
def new_review(request, bookname_id):
    '''add a new review for a certain book'''
    review=Book.objects.get(id=bookname_id)
    if request.method!='POST':
        #no data submitted -> create blank form
        form=ReviewForm()
    else:
        #post the submitted data->process data
        form=ReviewForm(data=request.POST)
        if form.is_valid():
            new_review=form.save(commit=False)
            new_review.bookname=bookname
            new_review.save()
            return redirect('crazy_book_club_app:bookname',bookname_id=bookname_id)
    #display blank or invalid form
    context={'bookname':bookname, 'form':form}
    return render(request,'crazy_book_club_app/new_review.html',context)

@login_required
def edit_review(request, review_id):
    '''edit existing review'''
    review=Review.objects.get(id=review_id)
    bookname=review.bookname
    if bookname.owner!=request.user:
        raise Http404
    if request.method!='POST':
        #initial request must fill out form
        form=ReviewForm(instance=review)
    else:
        #post data submitted
        form=ReviewForm(instance=review, data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('crazy_book_club_app:bookname', bookname_id=bookname.id)
    context= {'review':review, 'bookname':bookname,'form':form}
    return render(request,'crazy_book_club_app/edit_review.html',context)

crazy_book_club_app/templates/crazy_book_club_app/base.html
<p>
    <a href="{% url 'crazy_book_club_app:index' %}">Crazy Book Club</a> -
    <a href="{% url 'crazy_book_club_app:booknames' %}">Book Names</a> -


    {% if user.is_authenticated %} 
        Hello, {{ user.username }}. -
        <a href="{% url 'users:logout' %}">Log out</a>
    {% else %} 
        <a href="{% url 'users:register' %}"> Register </a> -
        <a href="{% url 'users:login' %}"> Log in </a>  <!-- url, not urls as in instructions-->
    {% endif %} 
</p>

{% block content %} {% endblock content %}

crazy_book_club_app/templates/crazy_book_club_app/bookname.html
<!--This page shows all reviews for a particular book -->

{% extends 'crazy_book_club_app/base.html' %}

{% block content %} 

<p>Bookname: {{ bookname }} </p>

<p>Reviews:</p>
<p>
    <a href="{% url 'crazy_book_club_app:new_review' bookname.id %}">Add a new review</a>
</p>
    <ul>
        {% for review in reviews %} 
            <li>
                <p>{{ review.date_added|date:'M d, Y H:i' }}</p>
                <p>{{ review.text|linebreaks }}</p>
                <p>
                    <a href="{% url 'crazy_book_club_app:edit_review' review.id %}">Edit review</a>
                </p>
            </li>
        {% empty %} 
            <li>There are no reviews for this book yet.</li>
        {% endfor %} 
    </ul>
{% endblock content %} 

crazy_book_club_app/templates/crazy_book_club_app/booknames.html
<!-- this page lists all books that have been listed on the db-->

{% extends "crazy_book_club_app/base.html" %}

{% block content %}

<p>Revieved book names: </p>

    <ul>
        {% for bookname in booknames %}
            <li>
                <a href="{% url 'crazy_book_club_app:bookname' bookname.id %}">{{ bookname }}</a>
            </li>
        {% empty %}
            <li> No books have been added yet. </li>
        {% endfor %}

    </ul>

<!-- adding a new book-->
    <a href="{% url 'crazy_book_club_app:new_book' %}">Add a new book</a>

{% endblock content %}

crazy_book_club_app/templates/crazy_book_club_app/edit_review.html
{% extends "crazy_book_club_app/base.html" %}
{% block content %}
    <p><a href="{% url 'crazy_book_club_app:bookname' bookname.id %}">{{bookname}}</a></p>

    <p> Edit a review:</p>
    <form action="{% url 'crazy_book_club_app:edit_review' review.id %}" method='post'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Save changes</button>
    </form>
{% endblock content %}

crazy_book_club_app/templates/crazy_book_club_app/index.html
<!--<p>Crazy Book Club</p>

<p>Crazy Book Club gives you a chance to
log your books onto a web page. </p>
-->

{% extends "crazy_book_club_app/base.html" %}

{% block content %}

<p>Crazy Book Club gives you a chance to
    log your books onto a web page. </p>

{% endblock content %}

crazy_book_club_app/templates/crazy_book_club_app/new_book.html
<!-- template for a site which allows users to add a book via a form-->

{% extends "crazy_book_club_app/base.html" %} 
{% block content %} 
    <p> Add a new book:</p>
    <form action="{% url 'crazy_book_club_app:new_book' %}" method='POST'> <!--??? post or POST-->
        {% csrf_token %} 
        {{ form.as_p }} 
        <button name="submit">Add book</button>
    </form>
{% endblock content %} 

crazy_book_club_app/templates/crazy_book_club_app/new_review.html
<!-- template for a site which allows users to add a review to a pre-existing book
     via a form-->

{% extends "crazy_book_club_app/base.html" %} 
{% block content %} 
<p><a href="{% url 'crazy_book_club_app:bookname' bookname.id %}">{{bookname}}</a></p>
    <p> Add a new review:</p>
    <form action="{% url 'crazy_book_club_app:new_review' bookname.id %}" method='POST'>
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">Add review</button>
    </form>
{% endblock content %}